project:
  type: website

website:
  title: "ASAM135 Project"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
        
    right: 
      - text: Education (Julia)
      - menu: 
          - text: Interview Transcripts 
          - interviewmom.qmd 

format:
  html:
    theme: sandstone
    toc: true
